##---------------------------------------------------------------------##
# Simulation parameters
simulation:
  total_time: 50
  current_time: 0
  time_step: 0.25
  headless: False
  collision_free: True
  n_buildings: 15
  n_nodes: 53
  n_targets: 3
  goal_node: [39]
  target_building_id: [38, 39, 40]
  n_ugv: 25
  n_uav: 75
  n_uav_clusters: 3
  n_ugv_clusters: 3
  n_uav_platoons: 3
  n_ugv_platoons: 3
##---------------------------------------------------------------------##
# UAV and UGV parameters
uav:
  speed: 10.0
  search_speed: 2.0
  search_dist: 20
  max_formation_size: 10
ugv:
  speed: 7.0
  search_speed: 1.0
  defense_radius: 3
  max_formation_size: 10
  coef_slowness: 1.2
##---------------------------------------------------------------------##
# Weigths parameters
weights:
  w_cluster_battery_pos: 1
  w_cluster_ammo_pos: 1
  w_search: 1
  w_time_uav: 0.05 #  reward weight asssociated with time to goal for UAVs
  w_battery_uav: 0 # weight of battery in reward
  w_time_ugv: 0.01 #  reward weight asssociated with time to goal for UGVs
  w_ammo_ugv: 0 # weight of ammo in reward
##---------------------------------------------------------------------##
# State parameters
state:
  n_keep_in_pareto: 5
##---------------------------------------------------------------------##
# Reward parameters
reward:
  progress_reward: 10
  indoor_reward: 20
  succssess_reward: 100
##---------------------------------------------------------------------##
# Neural network parameters
network:
  n_states: 37
  n_actions: 18
  n_epochs: 50
  n_episodes: 1000
  batch_size: 64
  learning_rate: 0.001
  drop_out: 0.10
  gamma: 0.45
##---------------------------------------------------------------------##
# Primitive parameters
primitive:
  uav:
    n_uav_primitive: 2
    n_formations: 2
    max_size: 2
    n_caution_status: 3
  ugv:
    n_ugv_primitive: 2
    n_formations: 2
    max_size: 2
    n_caution_status: 4
##---------------------------------------------------------------------##
# Primitive parameters
red_team:
  sigma: 1
  mue: 0.1
##---------------------------------------------------------------------##
# Paths
map_data_path: 'data/processed/map_data/'
map_save_path: 'data/processed/map_data/'
log_path: 'data/log/'
rrt_data_path: 'data/processed/map_data/rrt'
graph_save_path: 'data/processed/map_data/'
##---------------------------------------------------------------------##
# Paths
record_video: False
log_states: False
